name: Publish Docker image

on:
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          # using PAT on dockerhub
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ""


      - name: Build and push Docker image
        uses: docker/build-push-action@v21
        with:
          context: .
          push: true
          tags: "nandiheath/kube-log-viewer:${{ github.sha }}"
